# Generated by Django 6.0.2 on 2026-03-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('audio', 'Audio'), ('text', 'Text')], max_length=10)),
                ('filename', models.CharField(blank=True, max_length=255, null=True)),
                ('transcript_json', models.JSONField()),
                ('audit_json', models.JSONField()),
                ('overall_score', models.IntegerField()),
                ('sentiment', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
