"""
Django settings for django_backend project.
Generated by 'django-admin startproject' using Django 4.2.28.
"""

import os
from pathlib import Path
import dj_database_url

# Base directory
BASE_DIR = Path(__file__).resolve().parent.parent


# SECURITY
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "temporary-secret-key")

DEBUG = False

ALLOWED_HOSTS = ["*"]


# APPLICATIONS
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'corsheaders',

    'processor',

    # ── Milestone 3 & 4 additions (additive only) ──
    'channels',
    'rag.apps.RagConfig',


    'alerts.apps.AlertsConfig',
    'realtime',
]


# MIDDLEWARE
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',

    'whitenoise.middleware.WhiteNoiseMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'django_backend.urls'


# TEMPLATES
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'django_backend.wsgi.application'


# DATABASE (PostgreSQL from Neon with SQLite fallback)
DATABASE_URL = os.environ.get("DATABASE_URL")
if not DATABASE_URL:
    DATABASE_URL = f"sqlite:///{str(BASE_DIR / 'db.sqlite3').replace(os.sep, '/')}"

DATABASES = {
    "default": dj_database_url.parse(
        DATABASE_URL,
        conn_max_age=600,
        ssl_require=False if "sqlite" in DATABASE_URL else True
    )
}


# PASSWORD VALIDATION
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# INTERNATIONALIZATION
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# STATIC FILES
STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


# DEFAULT PRIMARY KEY
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# CORS
CORS_ALLOW_ALL_ORIGINS = True

# ══════════════════════════════════════════════════════════════════════
# Milestone 3 & 4 — New configuration (additive only)
# ══════════════════════════════════════════════════════════════════════

# Django Channels — ASGI real-time support
ASGI_APPLICATION = 'django_backend.routing.application'

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    }
}
# Production: swap to Redis-backed layer:
# CHANNEL_LAYERS = {
#     "default": {
#         "BACKEND": "channels_redis.core.RedisChannelLayer",
#         "CONFIG": {"hosts": [os.environ.get("REDIS_URL", "redis://localhost:6379")]},
#     }
# }

# Milvus vector database
# Dev/Demo : MILVUS_URI=./milvus_local.db  (Milvus Lite — no server needed)
# Production: MILVUS_URI=grpc://milvus:19530 (Milvus Standalone)
MILVUS_URI = os.environ.get("MILVUS_URI")
if not MILVUS_URI:
    try:
        import milvus_lite
        MILVUS_URI = "./milvus_local.db"
    except ImportError:
        # Default to a mock/empty URI to avoid pymilvus validation errors during startup if no server is intended
        MILVUS_URI = "http://localhost:19530" 

MILVUS_TOKEN = os.environ.get("MILVUS_TOKEN", "")

# Alert dispatch
ALERT_WEBHOOK_URL = os.environ.get("ALERT_WEBHOOK_URL", "")

# LLM Provider (openrouter | openai | groq | together)
ACTIVE_LLM_PROVIDER  = os.environ.get("ACTIVE_LLM_PROVIDER", "openrouter")
MAX_TOKENS_PER_AUDIT = os.environ.get("MAX_TOKENS_PER_AUDIT", "1500")