# Generated by Django 4.2.28 on 2026-03-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_id', models.IntegerField(db_index=True)),
                ('agent_id', models.CharField(default='unknown', max_length=64)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('WARNING', 'Warning'), ('INFO', 'Info')], db_index=True, max_length=16)),
                ('rule_name', models.CharField(max_length=128)),
                ('description', models.TextField(default='')),
                ('payload', models.JSONField(default=dict)),
                ('dispatched', models.BooleanField(default=False)),
                ('reviewed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['severity', 'created_at'], name='alerts_aler_severit_a18a12_idx'), models.Index(fields=['audit_id'], name='alerts_aler_audit_i_cc38e2_idx')],
            },
        ),
    ]
